home/urls.py
from django.urls import include, path, re_path
from . import views

#from django.conf.urls import url #, include

app_name = 'home'

urlpatterns = [
    path('index', views.HomeView.as_view(), name='index'),
    path('usuarios', views.CrearUsuarioView.as_view(), name='usuarios'),
    re_path(r'^editar-usuario/(?P<pk>\d+)$', views.EditarUsuarioView.as_view(), name='editar_usuario'),
    re_path(r'^eliminar-usuario/(?P<pk>\d+)$', views.EliminarUsuarioView.as_view(), name='eliminar_usuario'),
    path('cargar-pdf', views.CargarPdfView.as_view(), name='cargar_pdf'),
]

mytest/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from home.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', HomeView.as_view(), name='inicio'),
    path('home/', include('home.urls'), name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.encoding import smart_str

from datetime import datetime
import os

# Create your models here.

class PerfilUsuario(models.Model):
    tipo = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return "{} ".format(str(self.tipo))


class Usuario(AbstractUser):
    #CLIENTE = 1
    #ADMINISTRADOR = 2
    #PERFILES = ((CLIENTE, 'CLIENTE'), (ADMINISTRADOR, 'ADMINISTRADOR'))
    #perfil = models.PositiveIntegerField(choices=PERFILES, default=CLIENTE)

    perfil = models.ForeignKey(PerfilUsuario, on_delete=models.CASCADE)

    def __str__(self):
        return "{} ({})".format(str(self.username), str(self.perfil))


class ArchivosPdf(models.Model):

    def generate_filename(self, filename):
        fecha = datetime.now()
        path = "documentos_pdf/%s/%s" % (fecha.date(), smart_str(filename))
        return path

    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, null=True, blank=True)
    pdf_uno = models.FileField(null=True, blank=True, upload_to=generate_filename, max_length=500)
    pdf_dos = models.FileField(null=True, blank=True, upload_to=generate_filename, max_length=500)

    def get_name_pdf_uno(self):
        return os.path.basename(self.pdf_uno.name)

    def get_name_pdf_dos(self):
        return os.path.basename(self.pdf_dos.name)

home/forms.py
from django import forms
from home.models import Usuario, ArchivosPdf

from django.core.validators import FileExtensionValidator


class UsuarioForm(forms.ModelForm):
    """
    Autor: Duvernei
    Fecha: 2021-11
    Formulario para creacion/actualizacion de usuario
    """
    def __init__(self, *args, **kwargs):
        super(UsuarioForm, self).__init__(*args, **kwargs)
        self.fields['password'].widget = forms.PasswordInput(render_value=True)

    class Meta:
        model = Usuario
        fields = ('username', 'password', 'email', 'perfil')


class CargueArchivoForm(forms.ModelForm):
    """
    Autor: Duvernei
    Fecha: 2021-11
    Formulario para el cargue de archivos pdf
    """
    def __init__(self, *args, **kwargs):
        super(CargueArchivoForm, self).__init__(*args, **kwargs)
        self.fields['pdf_uno'] = forms.FileField(validators=[
            FileExtensionValidator(allowed_extensions=['pdf'],
                                   message="La extensión del archivo '%(extension)s' no esta permitida. "
                                           "Las extensiones permitida son: '%(allowed_extensions)s'.")])
        self.fields['pdf_dos'] = forms.FileField(validators=[
            FileExtensionValidator(allowed_extensions=['pdf'],
                                   message="La extensión del archivo '%(extension)s' no esta permitida. "
                                           "Las extensiones permitida son: '%(allowed_extensions)s'.")])

    class Meta:
        model = ArchivosPdf
        fields = ('pdf_uno', 'pdf_dos')

home/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic import CreateView, UpdateView, TemplateView, View, FormView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages

from .models import Usuario, ArchivosPdf
from .forms import UsuarioForm, CargueArchivoForm

# Create your views here.

class HomeView(LoginRequiredMixin, TemplateView):
    """
    autor: Duvernei
    fecha: 2021-11
    descripcion: Pagina de inicio

    """
    template_name = 'home/index.html'


class CrearUsuarioView(LoginRequiredMixin, CreateView):
    """
    autor: Duvernei
    fecha: 2021-11
    descripcion: Pagina de crear usuario
    """
    model = Usuario
    form_class = UsuarioForm
    template_name = 'home/gestion_usuarios.html'

    def dispatch(self, request, *args, **kwargs):
        usuario = get_object_or_404(Usuario, id=request.user.id)
        if usuario.perfil.tipo != 'ADMINISTRADOR':
            messages.error(self.request, "Usted no tiene permisos para gestionar usuarios")
            return redirect(reverse('inicio', kwargs={}))
        return super(CrearUsuarioView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_users'] = Usuario.objects.all()
        return context

    def form_valid(self, form):
        usuario = form.save(commit=False)
        usuario.set_password(usuario.password)
        messages.success(self.request, "Usuario registrado correctamente")
        return super(CrearUsuarioView, self).form_valid(form)

    def get_success_url(self):
        return reverse('home:usuarios', kwargs={})


class EditarUsuarioView(LoginRequiredMixin, UpdateView):
    """
    autor: Duvernei
    fecha: 2021-11
    descripcion: Pagina de editar usuario
    """
    model = Usuario
    form_class = UsuarioForm
    template_name = 'home/gestion_usuarios.html'

    def dispatch(self, request, *args, **kwargs):
        usuario = get_object_or_404(Usuario, id=request.user.id)
        if usuario.perfil.tipo != 'ADMINISTRADOR':
            messages.error(self.request, "Usted no tiene permisos para gestionar usuarios")
            return redirect(reverse('inicio', kwargs={}))
        return super(EditarUsuarioView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_users'] = Usuario.objects.all()
        return context

    def form_valid(self, form):
        usuario = form.save(commit=False)
        if 'password' in form.changed_data:
            usuario.set_password(usuario.password)
        messages.success(self.request, "Usuario actualizado correctamente")
        return super(EditarUsuarioView, self).form_valid(form)
    
    def get_success_url(self):
        return reverse('home:usuarios', kwargs={})


class EliminarUsuarioView(LoginRequiredMixin, View):
    """
    autor: Duvernei
    fecha: 2021-11
    descripcion: Pagina de eliminar usuario
    """
    def dispatch(self, request, *args, **kwargs):
        usuario = get_object_or_404(Usuario, id=request.user.id)
        if usuario.perfil.tipo != 'ADMINISTRADOR':
            messages.error(self.request, "Usted no tiene permisos para gestionar usuarios")
            return redirect(reverse('inicio', kwargs={}))
        return super(EliminarUsuarioView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        usuario = get_object_or_404(Usuario, id=self.kwargs['pk'])
        usuario.delete()
        return redirect(reverse('home:usuarios', kwargs={}))


class CargarPdfView(LoginRequiredMixin, FormView):
    """
    autor: Duvernei
    fecha: 2021-11
    descripcion: Pagina de carga de pdf

    """
    #permission_required = 'home.add_archivospdf'
    template_name = 'home/cargar_pdf.html'
    form_class = CargueArchivoForm

    def form_valid(self, form):
        archivospdf = form.save(commit=False)
        archivospdf.usuario = self.request.user
        archivospdf.save()
        messages.success(self.request, "Archivos pdf cargados correctamente")
        return redirect(reverse('home:cargar_pdf', kwargs={}))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        archivos = ArchivosPdf.objects.filter(usuario=self.request.user)
        if self.request.user.perfil.tipo == 'ADMINISTRADOR':
            archivos = ArchivosPdf.objects.all()
        context['list_files'] = archivos
        return context

templates/base_generic.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title_page %} Home {% endblock title_page %}</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'assets/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'assets/css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/plugins/toastr/build/toastr.min.css' %}" rel="stylesheet" type="text/css"/>

    {% block css %} {% endblock css %}

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Test <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'inicio' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Inicio</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Menú
            </div>

            {% block navigation %}

            <li class="nav-item">
                <a class="nav-link" href="{% url 'home:usuarios' %}">
                    <i class="fas fa-fw fa-child"></i>
                    <span>Gestionar Usuarios</span></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'home:cargar_pdf' %}">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Cargar pdf</span></a>
            </li>

            {% endblock navigation %}
  
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Cuenta</span>
                                <img class="img-profile rounded-circle"
                                    src="{% static 'assets/img/undraw_profile.svg' %}">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">{% block title_panel %} Inicio {% endblock title_panel %}</h1>
                        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" data-toggle="modal" data-target="#logoutModal"><i
                                class="fas fa-power-off fa-sm text-white-50"></i> logout now</a>
                    </div>

                    {% block content %} {% endblock content %}

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a href="{% url 'logout' %}" class="btn btn-primary">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'assets/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'assets/js/sb-admin-2.min.js' %}"></script>

    <script src="{% static 'assets/plugins/toastr/build/toastr.min.js' %}"></script>

    {% block javascript %}{% endblock javascript %}

    <script>
        $(document).ready(function () {
            {% for m in messages %}
                toastr["{{ m.tags }}"]('{{ m }}');
            {% endfor %}
        });
    </script>

</body>

</html>

templates/base_login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title_page %} Login {% endblock title_page %}</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'assets/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'assets/css/sb-admin-2.min.css' %}" rel="stylesheet">

    <style type="text/css">
    </style>

</head>

<body class="bg-gradient-primary">

    {% block content %}

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">
                                            {% block titlecard %} Welcome Back! {% endblock titlecard %}
                                        </h1>
                                    </div>
                                    {% block form %} {% endblock form %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    {% endblock content %}

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'assets/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'assets/js/sb-admin-2.min.js' %}"></script>

    {% block javascript %} {% endblock javascript %}

</body>

</html>

templates/home/cargar_pdf.html
{% extends "base_generic.html" %}
{% load static %}

{% block css %}
	<link href="{% static 'assets/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
	<style type="text/css">
		table td {
			word-wrap: break-word;
			max-width: 250px;
		}
	</style>
{% endblock %}

{% block title_panel %} Cargar pdf {% endblock %}

{% block content %}

<div class="row">
	<div class="col-sm-4">
		<h4>{% if object %}Editar {% else %}Registrar {% endif %} archivos pdf</h4><hr>
	  {% if form.errors %}
	  <p>Please try again.</p>
	  <p>{{ form.errors }}</p>
	  {% endif %}

	  <form method="post" enctype="multipart/form-data">
		  {% csrf_token %}
		  <div>
		    <div>{{ form.pdf_uno.label_tag }}</div>
		    <div>{{ form.pdf_uno }}</div>
		  </div><br>
		  <div>
		    <div>{{ form.pdf_dos.label_tag }}</div>
		    <div>{{ form.pdf_dos }}</div>
		  </div><br>

		  <div>
		    <input type="submit" value="GUARDAR" class="btn btn-primary btn-user btn-block" />
		    <input type="hidden" name="next" value="{{ next }}" />
		  </div>
	  </form>
	</div>
	<div class="col-sm-8">
		<h4>Lista de archivos</h4><hr>
		<table class="table datatable">
			<thead>
				<tr>
					<th>usuario</th>
					<th>archivos</th>
					<th>acciones</th>
				</tr>
			</thead>
			<tbody>
				{% for registro in list_files %}
				<tr>
					<td>{{ registro.usuario.username }}</td>
					<td>
						[1] <a href="{{ registro.pdf_uno.url }}">{{ registro.get_name_pdf_uno }}</a><br>
						[2] <a href="{{ registro.pdf_dos.url }}">{{ registro.get_name_pdf_dos }}</a>
					</td>
					<td>
						<label>Por definir</label>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>

{% endblock %}

{% block javascript %}
    <script src="{% static 'assets/vendor/datatables/jquery.dataTables.min.js' %}"></script>
	<script src="{% static 'assets/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
	<script type="text/javascript">
		$(document).ready(function () {
            $('.datatable').DataTable({});
        });
	</script>
{% endblock %}

templates/home/gestion_usuarios.html
{% extends "base_generic.html" %}
{% load static %}

{% block css %}
	<link href="{% static 'assets/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block title_panel %} Gestión de usuarios {% endblock %}

{% block content %}

<div class="row">
	<div class="col-sm-4">
		<h4>{% if object %}Editar {% else %}Registrar {% endif %} usuario</h4><hr>
	  {% if form.errors %}
	  <p>Please try again.</p>
	  <p>{{ form.errors }}</p>
	  {% endif %}

	  <form method="post">
		  {% csrf_token %}
		  <div>
		    <div>{{ form.username.label_tag }}</div>
		    <div>{{ form.username }}</div>
		  </div><br>
		  <div>
		    <div>{{ form.password.label_tag }}</div>
		    <div>{{ form.password }}</div>
		  </div><br>
		  <div>
		    <div>{{ form.email.label_tag }}</div>
		    <div>{{ form.email }}</div>
		  </div><br>
		  <div>
		    <div>{{ form.perfil.label_tag }}</div>
		    <div>{{ form.perfil }}</div>
		  </div><br>

		  <div>
		    <input type="submit" value="GUARDAR" class="btn btn-primary btn-user btn-block" />
		    <input type="hidden" name="next" value="{{ next }}" />
		  </div>
	  </form>
	</div>
	<div class="col-sm-8">
		<h4>Lista de usuarios</h4><hr>
		<table class="table datatable">
			<thead>
				<tr>
					<th>usuario</th>
					<th>perfil</th>
					<th>email</th>
					<th>acciones</th>
				</tr>
			</thead>
			<tbody>
				{% for user in list_users %}
				<tr>
					<td>{{ user.username }}</td>
					<td>{{ user.perfil.tipo }}</td>
					<td>{{ user.email }}</td>
					<td>
						<a href="{% url 'home:editar_usuario' user.id %}" class="btn btn-primary btn-icon btn-circle btn-sm">
							<i class="fa fa-edit"></i>
						</a>
						<a href="{% url 'home:eliminar_usuario' user.id %}" class="btn btn-danger btn-icon btn-circle btn-sm">
							<i class="fa fa-trash"></i>
						</a>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>

{% endblock %}

{% block javascript %}
    <script src="{% static 'assets/vendor/datatables/jquery.dataTables.min.js' %}"></script>
	<script src="{% static 'assets/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
	<script type="text/javascript">
		$(document).ready(function () {
            $('table.datatable').DataTable();
        });
	</script>
{% endblock %}

templates/home/index.html
{% extends "base_generic.html" %}